# Generated by Django 4.1.7 on 2023-02-23 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_booking_comment_remove_booking_guest_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 23, 15, 8, 42, 860142, tzinfo=datetime.timezone.utc)),
        ),
    ]
