# Generated by Django 4.1.7 on 2023-02-24 03:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_booking_reservation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.TimeField(choices=[(datetime.time(14, 0), '14:00:00'), (datetime.time(14, 30), '14:30:00'), (datetime.time(15, 0), '15:00:00'), (datetime.time(15, 30), '15:30:00'), (datetime.time(16, 0), '16:00:00'), (datetime.time(16, 30), '16:30:00'), (datetime.time(17, 0), '17:00:00'), (datetime.time(17, 30), '17:30:00'), (datetime.time(18, 0), '18:00:00'), (datetime.time(18, 30), '18:30:00'), (datetime.time(19, 0), '19:00:00'), (datetime.time(19, 30), '19:30:00'), (datetime.time(20, 0), '20:00:00'), (datetime.time(20, 30), '20:30:00'), (datetime.time(21, 0), '21:00:00'), (datetime.time(21, 30), '21:30:00'), (datetime.time(22, 0), '22:00:00'), (datetime.time(22, 30), '22:30:00')], default=datetime.time(22, 30)),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('reservation_date', 'reservation_time', 'reservation_slot')},
        ),
    ]
